/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_dsm.h"


void
testprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	para_1  write_data_1_arg;
	int  *result_2;
	para_2  read_data_1_arg;
	int  *result_3;
	para_3  delete_data_1_arg;
	int  *result_4;
	para_4  recover_data_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = write_data_1(&write_data_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = read_data_1(&read_data_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = delete_data_1(&delete_data_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = recover_data_1(&recover_data_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
rm_write_data(char *host, void* param)
{
	CLIENT *clnt;
	int  *result_1;
	para_1  *write_data_1_arg = (para_1*)param;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		// exit (1);
		return 1;
	}
#endif	/* DEBUG */

	result_1 = write_data_1(write_data_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		clnt_destroy (clnt);
		return 2;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

int
rm_read_data(char *host, void* param)
{
	CLIENT *clnt;
	int  *result_2;
	para_2  *read_data_1_arg = (para_2*)param;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		// exit (1);
		return 1;
	}
#endif	/* DEBUG */

	result_2 = read_data_1(read_data_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		clnt_destroy (clnt);
		return 2;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_2;
}

int
rm_delete_data(char *host, void* param)
{
	CLIENT *clnt;
	int  *result_2;
	para_3  *read_data_1_arg = (para_3*)param;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		// exit (1);
		return 1;
	}
#endif	/* DEBUG */

	result_2 = delete_data_1(read_data_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		clnt_destroy (clnt);
		return 2;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_2;
}

int
rm_recover_data(char *host, void* param)
{
	CLIENT *clnt;
	int  *result_2;
	para_4  *read_data_1_arg = (para_4*)param;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		// exit (1);
		return 1;
	}
#endif	/* DEBUG */

	result_2 = recover_data_1(read_data_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		clnt_destroy (clnt);
		return 2;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_2;
}


// int
// main (int argc, char *argv[])
// {
// 	char *host;

// 	if (argc < 2) {
// 		printf ("usage: %s server_host\n", argv[0]);
// 		exit (1);
// 	}
// 	host = argv[1];
// 	testprog_1 (host);
// exit (0);
// }
