/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_dsm.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
testprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		para_1 write_data_1_arg;
		para_2 read_data_1_arg;
		para_3 delete_data_1_arg;
		para_4 recover_data_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case WRITE_DATA:
		_xdr_argument = (xdrproc_t) xdr_para_1;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) write_data_1_svc;
		break;

	case READ_DATA:
		_xdr_argument = (xdrproc_t) xdr_para_2;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) read_data_1_svc;
		break;

	case DELETE_DATA:
		_xdr_argument = (xdrproc_t) xdr_para_3;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) delete_data_1_svc;
		break;

	case RECOVER_DATA:
		_xdr_argument = (xdrproc_t) xdr_para_4;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) recover_data_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

// int
// main (int argc, char **argv)
// {
// 	register SVCXPRT *transp;

// 	pmap_unset (TESTPROG, VERSION);

// 	transp = svcudp_create(RPC_ANYSOCK);
// 	if (transp == NULL) {
// 		fprintf (stderr, "%s", "cannot create udp service.");
// 		exit(1);
// 	}
// 	if (!svc_register(transp, TESTPROG, VERSION, testprog_1, IPPROTO_UDP)) {
// 		fprintf (stderr, "%s", "unable to register (TESTPROG, VERSION, udp).");
// 		exit(1);
// 	}

// 	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
// 	if (transp == NULL) {
// 		fprintf (stderr, "%s", "cannot create tcp service.");
// 		exit(1);
// 	}
// 	if (!svc_register(transp, TESTPROG, VERSION, testprog_1, IPPROTO_TCP)) {
// 		fprintf (stderr, "%s", "unable to register (TESTPROG, VERSION, tcp).");
// 		exit(1);
// 	}

// 	svc_run ();
// 	fprintf (stderr, "%s", "svc_run returned");
// 	exit (1);
// 	/* NOTREACHED */
// }

void*
svcInit(void* arg) {
	register SVCXPRT *transp;

	pmap_unset (TESTPROG, VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TESTPROG, VERSION, testprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TESTPROG, VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TESTPROG, VERSION, testprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TESTPROG, VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}

int
rpcSvcInit() {
	pthread_t tid;
	int ret = 0;

	ret = pthread_create(&tid, NULL, svcInit, NULL);
	if(ret != 0) {
		printf("pthread_create error, ret = %d\n", ret);
	}
	pthread_detach (tid);
	printf("rpcSvcInit success\n");

	return 0;
}