/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_dsm.h"

bool_t
xdr_para_1 (XDR *xdrs, para_1 *objp)
{
	// register int32_t *buf;

	// int i;
	 if (!xdr_vector (xdrs, (char *)objp->buff, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_para_2 (XDR *xdrs, para_2 *objp)
{
	// register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_para_3 (XDR *xdrs, para_3 *objp)
{
	// register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_para_4 (XDR *xdrs, para_4 *objp)
{
	register int32_t *buf;

	// int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->buff, 2048,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->node))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->length))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->first))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->second))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->third))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->node);
			IXDR_PUT_LONG(buf, objp->num);
			IXDR_PUT_LONG(buf, objp->length);
			IXDR_PUT_LONG(buf, objp->first);
			IXDR_PUT_LONG(buf, objp->second);
			IXDR_PUT_LONG(buf, objp->third);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->buff, 2048,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->node))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->length))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->first))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->second))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->third))
				 return FALSE;
		} else {
			objp->node = IXDR_GET_LONG(buf);
			objp->num = IXDR_GET_LONG(buf);
			objp->length = IXDR_GET_LONG(buf);
			objp->first = IXDR_GET_LONG(buf);
			objp->second = IXDR_GET_LONG(buf);
			objp->third = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->buff, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->third))
		 return FALSE;
	return TRUE;
}
