/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DSM_H_RPCGEN
#define _RPC_DSM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct para_1 {
	char buff[1024];
	int len;
	int node;
};
typedef struct para_1 para_1;

struct para_2 {
	int node;
};
typedef struct para_2 para_2;

struct para_3 {
	int node;
};
typedef struct para_3 para_3;

struct para_4 {
	char buff[2048];
	int node;
	int num;
	int length;
	int first;
	int second;
	int third;
};
typedef struct para_4 para_4;

#define TESTPROG 87654321
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define WRITE_DATA 1
extern  int * write_data_1(para_1 *, CLIENT *);
extern  int * write_data_1_svc(para_1 *, struct svc_req *);
#define READ_DATA 2
extern  int * read_data_1(para_2 *, CLIENT *);
extern  int * read_data_1_svc(para_2 *, struct svc_req *);
#define DELETE_DATA 3
extern  int * delete_data_1(para_3 *, CLIENT *);
extern  int * delete_data_1_svc(para_3 *, struct svc_req *);
#define RECOVER_DATA 4
extern  int * recover_data_1(PARA_4 *, CLIENT *);
extern  int * recover_data_1_svc(PARA_4 *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WRITE_DATA 1
extern  int * write_data_1();
extern  int * write_data_1_svc();
#define READ_DATA 2
extern  int * read_data_1();
extern  int * read_data_1_svc();
#define DELETE_DATA 3
extern  int * delete_data_1();
extern  int * delete_data_1_svc();
#define RECOVER_DATA 4
extern  int * recover_data_1();
extern  int * recover_data_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_para_1 (XDR *, para_1*);
extern  bool_t xdr_para_2 (XDR *, para_2*);
extern  bool_t xdr_para_3 (XDR *, para_3*);
extern  bool_t xdr_para_4 (XDR *, para_4*);

#else /* K&R C */
extern bool_t xdr_para_1 ();
extern bool_t xdr_para_2 ();
extern bool_t xdr_para_3 ();
extern bool_t xdr_para_4 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DSM_H_RPCGEN */
