/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DSM_H_RPCGEN
#define _RPC_DSM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct para {
	char buff[1024];
	int len;
};
typedef struct para para;

#define TESTPROG 87654321
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define WRITE_DATA 1
extern  int * write_data_1(para *, CLIENT *);
extern  int * write_data_1_svc(para *, struct svc_req *);
#define READ_DATA 2
extern  int * read_data_1(para *, CLIENT *);
extern  int * read_data_1_svc(para *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WRITE_DATA 1
extern  int * write_data_1();
extern  int * write_data_1_svc();
#define READ_DATA 2
extern  int * read_data_1();
extern  int * read_data_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_para (XDR *, para*);

#else /* K&R C */
extern bool_t xdr_para ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DSM_H_RPCGEN */


